name: Issue 同步

on:
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      # - pinned
      # - unpinned
      - closed
      - reopened
      # - assigned
      # - unassigned
      - labeled
      - unlabeled
      - locked
      - unlocked
      # - milestoned
      # - demilestoned
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  sync:
    name: Issue同步
    if: ${{ !github.event.issue.pull_request && !startsWith(github.event.comment.body, 'Link To' )}}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE: ${{ github.event.issue.number }}
      REPO: ${{ github.repository }}
      CURRENT_COMMENT: ${{ github.event.comment.body }}
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        shell: pwsh
        run: echo $env:GITHUB_CONTEXT
      - name: 执行脚本
        shell: pwsh
        run: |
          # 获取Issue信息
          $issue_uri = "https://api.github.com/repos/$env:REPO/issues/$env:ISSUE"
          $comments_uri = "$issue_uri/comments"
          $token = ConvertTo-SecureString -AsPlainText $env:GITHUB_TOKEN
          $response = Invoke-WebRequest -Uri $issue_uri -Authentication Bearer -Token $token
          $issue = $response.Content | ConvertFrom-Json
          # 标题
          $issue.title
          # 创建日期
          $issue.created_at
          # 更新日期
          $issue.updated_at
          # 创建人
          $issue.user.login
          # 状态
          $issue.state
          # 标签
          $issue.labels | ForEach-Object { $_.name }
          # 内容
          $issue.body

          # 评论
          if($issue.comments -gt 0){
            $response = Invoke-WebRequest -Uri $comments_uri -Authentication Bearer -Token $token
            $response.Content | ConvertFrom-Json | ForEach-Object {
              # 创建人
              $_.user.login
              # 创建日期
              $_.created_at
              # 更新日期
              $_.updated_at
              # 内容
              $_.body
              $no_comment = $no_comment -or $_.body.StartsWith('Link To')
            }
          }
          if(!$no_comment){
            $req = @{ body = "Link To [#$env:ISSUE]($($issue.html_url))" } | ConvertTo-Json
            $response = Invoke-WebRequest -Method POST -Uri $comments_uri -Authentication Bearer -Token $token -Body $req
          }
