name: Issue 同步

on:
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      - pinned
      - unpinned
      - closed
      - reopened
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - locked
      - unlocked
      - milestoned
      - demilestoned
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  sync:
    name: Issue同步
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE: ${{ github.event.issue.number }}
      REPO: ${{ github.repository }}
    steps:
      - name: 执行脚本
        shell: pwsh
        run: |
          # 真的不容易啊
          $token = ConvertTo-SecureString -AsPlainText "$env:GITHUB_TOKEN"
          $response = Invoke-WebRequest -Uri "https://api.github.com/repos/$env:REPO/issues/$env:ISSUE" -Authentication Bearer -Token $token
          $data = $response.Content | ConvertFrom-Json
          $title = $data.title
          $user = $data.user.login
          $content = $data.body
          $state = $data.state
          Write-Host $title -ForegroundColor Yellow
          Write-Host $state -ForegroundColor Yellow
          Write-Host $user -ForegroundColor Yellow
          Write-Host $content -ForegroundColor Yellow

