name: Issue 同步

on:
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      # - pinned
      # - unpinned
      - closed
      - reopened
      # - assigned
      # - unassigned
      - labeled
      - unlabeled
      - locked
      - unlocked
      # - milestoned
      # - demilestoned
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  sync:
    name: Issue同步
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE: ${{ github.event.issue.number }}
      REPO: ${{ github.repository }}
    steps:
      - name: 执行脚本
        shell: pwsh
        run: |
          # 获取Issue信息
          $token = ConvertTo-SecureString -AsPlainText "$env:GITHUB_TOKEN"
          $response = Invoke-WebRequest -Uri "https://api.github.com/repos/$env:REPO/issues/$env:ISSUE" -Authentication Bearer -Token $token
          $issue = $response.Content | ConvertFrom-Json
          # 标题
          $issue.title
          # 创建日期
          $issue.created_at
          # 更新日期
          $issue.updated_at
          # 创建人
          $issue.user.login
          # 状态
          $issue.state
          # 标签
          $issue.labels | ForEach-Object { $_.name }
          # 内容
          $issue.body

          # 评论
          if($issue.comments > 0){
            $response = Invoke-WebRequest -Uri "https://api.github.com/repos/$env:REPO/issues/$env:ISSUE/comments" -Authentication Bearer -Token $token
            $response.Content | ConvertFrom-Json | ForEach-Object {
              # 创建人
              $_.user.login
              # 创建日期
              $_.created_at
              # 更新日期
              $_.updated_at
              # 内容
              $_.body
            }
          }


