name: Issue 同步

on:
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      - pinned
      - unpinned
      - closed
      - reopened
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - locked
      - unlocked
      - milestoned
      - demilestoned
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  sync:
    name: Issue同步
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ github.token }}
      ISSUE: ${{ github.event.issue.number }}
      REPO: ${{ github.repository }}
    steps:
      - name: 执行脚本
        shell: pwsh
        run: |
          if([string]::IsNullOrEmpty($env:SOME_TOKEN)){
            $token = ConvertTo-SecureString -AsPlainText "$env:TEST_TOKEN"
          } else {
            $token = ConvertTo-SecureString -AsPlainText "$env:SOME_TOKEN"
          }
          $response = Invoke-WebRequest -Uri "https://api.github.com/repos/$env:REPO/issues/$env:ISSUE" -Authentication Bearer -Token $token
          Write-Host $response.Content
          $data = $response.Content | ConvertFrom-Json
          $title = $data.title
          $content = $data.body

